### ISSUE TITLE
Connect to a specific port

### ISSUE THREAD

**Issue by yOPERO** [krohling/ArduinoWebsocketClient#6]
Nice project indeed!

I have been trying to figure out how to connect to a specific port in a websocket server.
Currently I do have a WS server with the echo sketch running on my LAN, the WS is open on port :1234

With Arduino ethernet shields in client mode there is this line:

client.connect(server, 80)

I have tried the same with your WS client but does not work

Ethernet.begin(mac, ip);
  client.connect(server, 1234);
  client.setDataArrivedDelegate(dataArrived);
  client.send("Hello World!");

Thanks in advanced for the help or hints you can provide me in order to solve it.

yOPERO

**Comment by krohling** [comment]
Hi, this should be possible.  Here's the signature for the connect method:
      bool connect(char hostname[], char path[] = "/", int port = 80);

To connect to a specific port try this:
     client.connect(server, "/", 1234);

-kevin

**Comment by yOPERO** [comment]
Kevin 

Thanks for your help it worked  nicely with servers on internet e.g. echo.websocket.org:80

But it did not work with the server in my  LAN (Autobahn for python) tomorrow I will look at it closely and compare why I am not getting connected to the WS server.

Would be really helpful if we could add a message when the connection is not stablished.

I will keep you updated with my findings if any.

**Comment by krohling** [comment]
Glad I could help.  If you want to print a message on Serial when the connection fails you could try something like this:

if(client.connect(server, "/", 1234) {
   Serial.println("Connected!");
}
else {
   Serial.println("Not Connected:(");
}
